### PR TITLE
Add py37, update pinnings

### PR DESCRIPTION
**Pull request by sdvillal**
Checklist
* [X] Used a fork of the feedstock to propose changes
* [X] Bumped the build number (if the version is unchanged)
* [X] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`

Builds packages against new pinnings and (hopefully) for python 3.7.

### CODE REVIEW

**Comment by sdvillal** [comment]
We are hitting several issues, at least:
- cython pin in the recipe makes some build envs unsolvable
- pyopengl broken: https://github.com/conda-forge/pyopengl-feedstock/issues/14

**Comment by matham** [comment]
Thanks for the PR. Here are some comments.

* Regarding the cython issue, we need to wait for a new kivy release because the max cython version in kivy master has been increased so it will be more compatible with recent cython.
* I'm not sure what the osx failure is all about - I'm not a mac user. The error seems to be:
  ```
  building 'kivy.core.image.img_imageio' extension
  creating build/temp.macosx-10.9-x86_64-3.6/private/tmp/pip-req-build-zog1i2ot/kivy/core/image
  x86_64-apple-darwin13.4.0-clang -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -I$PREFIX/include -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=${PREFIX}=/usr/local/src/conda-prefix -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -arch x86_64 -I/private/tmp/pip-req-build-zog1i2ot/kivy/include -I$PREFIX/include/python3.6m -c /private/tmp/pip-req-build-zog1i2ot/kivy/core/image/img_imageio.c -o build/temp.macosx-10.9-x86_64-3.6/private/tmp/pip-req-build-zog1i2ot/kivy/core/image/img_imageio.o -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks
  In file included from /private/tmp/pip-req-build-zog1i2ot/kivy/core/image/img_imageio.c:594:
  In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGDataProvider.h:8:
  In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:18:
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFAvailability.h:25:10: fatal error: 'os/availability.h' file not found
  #include <os/availability.h>
           ^~~~~~~~~~~~~~~~~~~
  1 error generated.
   error: command 'x86_64-apple-darwin13.4.0-clang' failed with exit status 1
  ```
* pyopengl is a dep on linux only. We can remove it because we don't actually depend on pyopengl. The only reason I included it originally is because it provided our missing dependencies, although at the time I didn't know what that was - it just seemed to make the build work. But looking at it, it's specifically `mesa`. We can remove pyopengl as a dependency and add [this ](https://github.com/conda-forge/pyopengl-feedstock/blob/master/recipe/yum_requirements.txt) file instead, which I think may be enough.
* I'm not sure about adding your user to the owners file because I'd like for the kivy devs only to have merge and release privileges, unless there's a reason to add someone outside kivy.

**Comment by sdvillal** [comment]
Thanks for the comments.

I have replaced pyopengl with libglu, if it works it is a better approach than using yum_requirements.

I have also removed myself from the maintainers.

Not a mac user myself, but since we need to wait until a new kivy version is released, that can wait too.

**Comment by sdvillal** [comment]
Will need to play a bit to get libgl recognized. Using yum_requirements will always work, but what is the conda-forge way?

From https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html:
*Note that what qualifies as a "system" dependency is a matter of opinion. The Anaconda Distribution chose not to provide X11 or GL packages, so we use CDT packages for X11. Conda-forge chose to provide X11 and GL packages.*

But see also: https://github.com/conda-forge/mesalib-feedstock/issues/16

In [r-gl they just consider it CDT](https://github.com/conda-forge/r-rgl-feedstock/pull/9). This is how their [meta.yaml](https://github.com/conda-forge/r-rgl-feedstock/blob/48c3f935b891a66e43c763b54f657744011abbe3/recipe/meta.yaml) currently looks like.

**Comment by matham** [comment]
Regarding cython, there's a high chance that simply changing `{{ pin_compatible('cython', lower_bound='0.23', upper_bound='0.28.2') }}` to `{{ pin_compatible('cython', lower_bound='0.23', upper_bound='0.29.7') }}` will work. I don't think there was cython specific fixes since the last release and master works with `0.29.7`. It's a worth a try to increase the max version and seeing if it compiles.

**Comment by sdvillal** [comment]
I have relaxed the cython upper bound. I just wonder, do we really need a cython upper bound by default?

conda-forge now documents nicely [how to build against libgl](http://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=libgl#libgl). Trying now with the CDTs at build time but without ```yum_requirements.txt```, since it seems to me we are using a gl mock for testing. I will add it after we get the building phase to succeed if it is actually needed.

**Comment by sdvillal** [comment]
The build now passes for linux. Left:
- deactivate python 3.7 build until a new kivy release is cut (@matham do you estimate that to be far?)
- fix the headers not being found in macos

**Comment by matham** [comment]
Regarding the cython max version thing. The reason for this is that cython makes frequent releases where they break backwards compatibility. This became such a frequent thing and we started getting enough issues, that we started tracking the max and min supported cython versions so that if an issue arises and someone installs kivy with too high of a cython version, we warn them about it in the log. It also helps us keep track of any breaking cython changes that we need to fix in our code.

For pip, we don't force the cython version except for a warning in the logs so that a user could downgrade cython if needed. For conda where we have to make sure it works for everyone, this means that if we don't have an upper limit, in a new cython release in the future kivy may stop working. So it is probably best if we pin the max version, and then we can make periodic new micro conda releases to increase the cython version if needed and supported.


For linux 3.7 before you disabled it, I'm not sure what the error was? All I could see was:

```
TEST START: /home/conda/feedstock_root/build_artifacts/linux-64/kivy-1.10.1-py37h2394fcc_2.tar.bz2
Renaming work directory,  /home/conda/feedstock_root/build_artifacts/kivy_1555990090151/work  to  /home/conda/feedstock_root/build_artifacts/kivy_1555990090151/work_moved_kivy-1.10.1-py37h2394fcc_2_linux-64
Collecting package metadata: ...working... done
Solving environment: ...working... failed
failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform linux-64: {"python[version='>=3.7,<3.8.0a0']", 'pillow', 'sdl2_ttf'}
WARNING:conda_build.build:failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform linux-64: {"python[version='>=3.7,<3.8.0a0']", 'pillow', 'sdl2_ttf'}
Tests failed for kivy-1.10.1-py37h2394fcc_2.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
```

It seems to have failed during the test phase. But if it managed to build it, maybe a test dependency is wrong? The issue though doesn't seem to require a new kivy release!?

Regarding an upcoming kivy release. I hope it'll happen soon, but I wouldn't be surprised if it takes at least a month.

**Comment by matham** [comment]
The osx issues seems to have been encountered by other people: https://github.com/kivy/kivy/issues/5345. A few people there claimed it was a cython version issue, but it's not clear if that really fixed that original issue.

I checked on travis, and it works fine there on osx. But we're using clang for it.

**Comment by sdvillal** [comment]
For that python 3.7 unsolvable env, we probably need to wait for (and maybe help with) [a new build of sdl2_ttf](https://github.com/conda-forge/sdl2_ttf-feedstock/pulls).

We probably need to think about our own pinnings of some libs (e.g. sdl2*). I think at the moment we let them float in without control.

If we get the python 3.7 package to build, can we assume it is safe to use for our current kivy release?

So should we try pinning cython to 0.26.1 in mac and see what happens?

And about cython pinning, I do not think it is very important. I might not understand it well, but once the package gets to build, can we, at runtime, forget about which cython version was used? If that is the case, and because this is a binary package, final users do not need to care about the specifics of the cython version used. So a loose version should then just be something that the recipe maintainers need to keep in mind when problems arise at build time. In fact, our current pin_compatible is simply equivalent to ```cython==0.29.7```.

**Comment by sdvillal** [comment]
Unfortunately using cython 0.26.1 in mac does not seem to help.

**Comment by sdvillal** [comment]
So checkpointing (I probably cannot come back to this anytime soon), I think we need to:

- [x] Re-enable python 3.7
- [x] Get sdl2_ttf to rebuild so tests can proceed in python  3.7.
- [x] Solve the header not found issue in osx
- [x] Revisit pinnings for other dependencies

**Comment by matham** [comment]
* I started the process of making a new sdl2/sdl2_ttf release (https://github.com/conda-forge/sdl2-feedstock/pull/12, https://github.com/conda-forge/sdl2_ttf-feedstock/pull/4).
* >If we get the python 3.7 package to build, can we assume it is safe to use for our current kivy release?

  Yes
* >And about cython pinning, I do not think it is very important

  Yeah, I agree I guess. It only affects us when making a new release on conda, as cython is not a runtime requirement.
* we can pin sdl2, but kivy doesn't really track it as we always use very recent sdl2 versions so I'm not sure what we'd be pinning it to.

**Comment by sdvillal** [comment]
I have enabled python 3.7 again (feel free to push changes too to the PR). Once the new sdl2 packages make it, tests should be able to proceed.

For pinning, in general we would need to know what the contract is for ABI/API incompatible changes on each library. In the concrete case of SDL I feel we lack enough data in [abi laboratory](https://abi-laboratory.pro/?view=timeline&l=sdl), as only "patch" version changes are reported in there. I would then pin to major directly in the sdl recipes like:

```yaml
build:
  number: 0
  run_exports:
    # likely major version compatibility
    # https://abi-laboratory.pro/?view=timeline&l=sdl
    - {{ pin_subpackage('sdl2', max_pin='x') }}
```

**Comment by matham** [comment]
BTW, I updated the sdl2 repos with the most recent sdl2 versions, including sdl2_ttf so 3.7 should be available now.

**Comment by sdvillal** [comment]
Yeah, green tick after sdl2 got updated, even for mac. Your good work repays.

I have cleaned up and force pushed. Once we get the green tick again, I feel we are ready to go for this PR.

I still would suggest to take care of pinning sdl2 in the original recipes and then rebuild to get these pins float here. I might open these PRs.

**Comment by matham** [comment]
Unfortunately, it looks like there's a new [sdl2 issue](https://github.com/conda-forge/sdl2-feedstock/issues/13), where sdl2 is now compiled without gl support. But this shouldn't affect the typical kivy user as we don't use sdl2's built in gl, unless asked by the user through an environment variable.

In any case, this shouldn't affect the kivy recipe, except if you pin the sdl2 version as a new sdl2 release will hopefully fix this soon (so you probably want to pin it to that new version!?).

**Comment by matham** [comment]
I just submitted a fix for the sdl2 issue, so you should be able to pin it as soon that's merged (and we confirm it works). In either case, I should probably merge this PR immediately!? Let me know and I'll merge it.

**Comment by sdvillal** [comment]
Green tick! Yes, I would just merge.

Actually, do you know if the sdl package being called "sdl2" means that we can parallel install different major versions of the sdl library? For example, if there even is an sdl3, could we install sdl2 and sdl3 versions together without breaking downstream? If so I think  pinning to major would not be needed at all to ensure that newer versions of sdl do not break old environment specs (because pinning is implicit in the lib name).

Indeed I guess the GL problem won't affect us, since as you describe it, it should only appear at runtime. So your new PR to sdl2 should just fix this without rebuild?

(disclaimer: I know little about these libs)

**Comment by matham** [comment]
>Actually, do you know if the sdl package being called "sdl2" means that we can parallel install different major versions of the sdl library?

Very likely. Because I believe the project itself was renamed to sdl2 after sdl2 was released. So it seems likely that a new sdl3 would just be a newer project. The shared binary is called `sdl2.dll` (on windows). I'm also doubtful that there would be a new sdl3 anytime soon. So yeah, there wouldn't be a need for pinning from that POV.

>So your new PR to sdl2 should just fix this without rebuild?

Correct.

**Comment by matham** [comment]
Thank you for all your hard work on this!

**Comment by sdvillal** [comment]
Perfect!

**Pull request merged**
